//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recargaqui
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TResponse", Namespace="http://tempuri.org/")]
    public partial class TResponse : object
    {
        
        private long transaction_idField;
        
        private int rcodeField;
        
        private string rcode_descriptionField;
        
        private string op_accountField;
        
        private string op_authorizationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long transaction_id
        {
            get
            {
                return this.transaction_idField;
            }
            set
            {
                this.transaction_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int rcode
        {
            get
            {
                return this.rcodeField;
            }
            set
            {
                this.rcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rcode_description
        {
            get
            {
                return this.rcode_descriptionField;
            }
            set
            {
                this.rcode_descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string op_account
        {
            get
            {
                return this.op_accountField;
            }
            set
            {
                this.op_accountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string op_authorization
        {
            get
            {
                return this.op_authorizationField;
            }
            set
            {
                this.op_authorizationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Recargaqui.transactSoap")]
    public interface transactSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTRequestID", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.GetTRequestIDResponse> GetTRequestIDAsync(Recargaqui.GetTRequestIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.GetTRequestResponse> GetTRequestAsync(Recargaqui.GetTRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.CheckTransactionResponse> CheckTransactionAsync(Recargaqui.CheckTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoT", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.DoTResponse> DoTAsync(Recargaqui.DoTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoC", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.DoCResponse> DoCAsync(Recargaqui.DoCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSkuList", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.GetSkuListResponse> GetSkuListAsync(Recargaqui.GetSkuListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<Recargaqui.GetBalanceResponse> GetBalanceAsync(Recargaqui.GetBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestID", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetTRequestIDRequestBody Body;
        
        public GetTRequestIDRequest()
        {
        }
        
        public GetTRequestIDRequest(Recargaqui.GetTRequestIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string licence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string terminalID;
        
        public GetTRequestIDRequestBody()
        {
        }
        
        public GetTRequestIDRequestBody(string username, string password, string licence, string terminalID)
        {
            this.username = username;
            this.password = password;
            this.licence = licence;
            this.terminalID = terminalID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetTRequestIDResponseBody Body;
        
        public GetTRequestIDResponse()
        {
        }
        
        public GetTRequestIDResponse(Recargaqui.GetTRequestIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTRequestIDResult;
        
        public GetTRequestIDResponseBody()
        {
        }
        
        public GetTRequestIDResponseBody(string GetTRequestIDResult)
        {
            this.GetTRequestIDResult = GetTRequestIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequest", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetTRequestRequestBody Body;
        
        public GetTRequestRequest()
        {
        }
        
        public GetTRequestRequest(Recargaqui.GetTRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string licence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string terminalID;
        
        public GetTRequestRequestBody()
        {
        }
        
        public GetTRequestRequestBody(string username, string password, string licence, string terminalID)
        {
            this.username = username;
            this.password = password;
            this.licence = licence;
            this.terminalID = terminalID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetTRequestResponseBody Body;
        
        public GetTRequestResponse()
        {
        }
        
        public GetTRequestResponse(Recargaqui.GetTRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTRequestResult;
        
        public GetTRequestResponseBody()
        {
        }
        
        public GetTRequestResponseBody(string GetTRequestResult)
        {
            this.GetTRequestResult = GetTRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransaction", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.CheckTransactionRequestBody Body;
        
        public CheckTransactionRequest()
        {
        }
        
        public CheckTransactionRequest(Recargaqui.CheckTransactionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTransactionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRequestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        public CheckTransactionRequestBody()
        {
        }
        
        public CheckTransactionRequestBody(string TRequestID, string username)
        {
            this.TRequestID = TRequestID;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.CheckTransactionResponseBody Body;
        
        public CheckTransactionResponse()
        {
        }
        
        public CheckTransactionResponse(Recargaqui.CheckTransactionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTransactionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Recargaqui.TResponse CheckTransactionResult;
        
        public CheckTransactionResponseBody()
        {
        }
        
        public CheckTransactionResponseBody(Recargaqui.TResponse CheckTransactionResult)
        {
            this.CheckTransactionResult = CheckTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoT", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.DoTRequestBody Body;
        
        public DoTRequest()
        {
        }
        
        public DoTRequest(Recargaqui.DoTRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoTRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRequestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string skuCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string op_account;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float monto;
        
        public DoTRequestBody()
        {
        }
        
        public DoTRequestBody(string TRequestID, string username, string skuCode, string op_account, float monto)
        {
            this.TRequestID = TRequestID;
            this.username = username;
            this.skuCode = skuCode;
            this.op_account = op_account;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoTResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.DoTResponseBody Body;
        
        public DoTResponse()
        {
        }
        
        public DoTResponse(Recargaqui.DoTResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoTResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Recargaqui.TResponse DoTResult;
        
        public DoTResponseBody()
        {
        }
        
        public DoTResponseBody(Recargaqui.TResponse DoTResult)
        {
            this.DoTResult = DoTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoC", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.DoCRequestBody Body;
        
        public DoCRequest()
        {
        }
        
        public DoCRequest(Recargaqui.DoCRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoCRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRequestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string skuCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string op_account;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int identificador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int idc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int idu;
        
        public DoCRequestBody()
        {
        }
        
        public DoCRequestBody(string TRequestID, string username, string skuCode, string op_account, float monto, int identificador, string clave, int idc, int idu)
        {
            this.TRequestID = TRequestID;
            this.username = username;
            this.skuCode = skuCode;
            this.op_account = op_account;
            this.monto = monto;
            this.identificador = identificador;
            this.clave = clave;
            this.idc = idc;
            this.idu = idu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoCResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.DoCResponseBody Body;
        
        public DoCResponse()
        {
        }
        
        public DoCResponse(Recargaqui.DoCResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoCResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Recargaqui.TResponse DoCResult;
        
        public DoCResponseBody()
        {
        }
        
        public DoCResponseBody(Recargaqui.TResponse DoCResult)
        {
            this.DoCResult = DoCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkuListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuList", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetSkuListRequestBody Body;
        
        public GetSkuListRequest()
        {
        }
        
        public GetSkuListRequest(Recargaqui.GetSkuListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkuListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetSkuListRequestBody()
        {
        }
        
        public GetSkuListRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkuListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetSkuListResponseBody Body;
        
        public GetSkuListResponse()
        {
        }
        
        public GetSkuListResponse(Recargaqui.GetSkuListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkuListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSkuListResult;
        
        public GetSkuListResponseBody()
        {
        }
        
        public GetSkuListResponseBody(string GetSkuListResult)
        {
            this.GetSkuListResult = GetSkuListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetBalanceRequestBody Body;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(Recargaqui.GetBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetBalanceRequestBody()
        {
        }
        
        public GetBalanceRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Recargaqui.GetBalanceResponseBody Body;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(Recargaqui.GetBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody()
        {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult)
        {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface transactSoapChannel : Recargaqui.transactSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class transactSoapClient : System.ServiceModel.ClientBase<Recargaqui.transactSoap>, Recargaqui.transactSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public transactSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(transactSoapClient.GetBindingForEndpoint(endpointConfiguration), transactSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public transactSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(transactSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public transactSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(transactSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public transactSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.GetTRequestIDResponse> Recargaqui.transactSoap.GetTRequestIDAsync(Recargaqui.GetTRequestIDRequest request)
        {
            return base.Channel.GetTRequestIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.GetTRequestIDResponse> GetTRequestIDAsync(string username, string password, string licence, string terminalID)
        {
            Recargaqui.GetTRequestIDRequest inValue = new Recargaqui.GetTRequestIDRequest();
            inValue.Body = new Recargaqui.GetTRequestIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.licence = licence;
            inValue.Body.terminalID = terminalID;
            return ((Recargaqui.transactSoap)(this)).GetTRequestIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.GetTRequestResponse> Recargaqui.transactSoap.GetTRequestAsync(Recargaqui.GetTRequestRequest request)
        {
            return base.Channel.GetTRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.GetTRequestResponse> GetTRequestAsync(string username, string password, string licence, string terminalID)
        {
            Recargaqui.GetTRequestRequest inValue = new Recargaqui.GetTRequestRequest();
            inValue.Body = new Recargaqui.GetTRequestRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.licence = licence;
            inValue.Body.terminalID = terminalID;
            return ((Recargaqui.transactSoap)(this)).GetTRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.CheckTransactionResponse> Recargaqui.transactSoap.CheckTransactionAsync(Recargaqui.CheckTransactionRequest request)
        {
            return base.Channel.CheckTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.CheckTransactionResponse> CheckTransactionAsync(string TRequestID, string username)
        {
            Recargaqui.CheckTransactionRequest inValue = new Recargaqui.CheckTransactionRequest();
            inValue.Body = new Recargaqui.CheckTransactionRequestBody();
            inValue.Body.TRequestID = TRequestID;
            inValue.Body.username = username;
            return ((Recargaqui.transactSoap)(this)).CheckTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.DoTResponse> Recargaqui.transactSoap.DoTAsync(Recargaqui.DoTRequest request)
        {
            return base.Channel.DoTAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.DoTResponse> DoTAsync(string TRequestID, string username, string skuCode, string op_account, float monto)
        {
            Recargaqui.DoTRequest inValue = new Recargaqui.DoTRequest();
            inValue.Body = new Recargaqui.DoTRequestBody();
            inValue.Body.TRequestID = TRequestID;
            inValue.Body.username = username;
            inValue.Body.skuCode = skuCode;
            inValue.Body.op_account = op_account;
            inValue.Body.monto = monto;
            return ((Recargaqui.transactSoap)(this)).DoTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.DoCResponse> Recargaqui.transactSoap.DoCAsync(Recargaqui.DoCRequest request)
        {
            return base.Channel.DoCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.DoCResponse> DoCAsync(string TRequestID, string username, string skuCode, string op_account, float monto, int identificador, string clave, int idc, int idu)
        {
            Recargaqui.DoCRequest inValue = new Recargaqui.DoCRequest();
            inValue.Body = new Recargaqui.DoCRequestBody();
            inValue.Body.TRequestID = TRequestID;
            inValue.Body.username = username;
            inValue.Body.skuCode = skuCode;
            inValue.Body.op_account = op_account;
            inValue.Body.monto = monto;
            inValue.Body.identificador = identificador;
            inValue.Body.clave = clave;
            inValue.Body.idc = idc;
            inValue.Body.idu = idu;
            return ((Recargaqui.transactSoap)(this)).DoCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.GetSkuListResponse> Recargaqui.transactSoap.GetSkuListAsync(Recargaqui.GetSkuListRequest request)
        {
            return base.Channel.GetSkuListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.GetSkuListResponse> GetSkuListAsync(string username, string password)
        {
            Recargaqui.GetSkuListRequest inValue = new Recargaqui.GetSkuListRequest();
            inValue.Body = new Recargaqui.GetSkuListRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Recargaqui.transactSoap)(this)).GetSkuListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Recargaqui.GetBalanceResponse> Recargaqui.transactSoap.GetBalanceAsync(Recargaqui.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Recargaqui.GetBalanceResponse> GetBalanceAsync(string username, string password)
        {
            Recargaqui.GetBalanceRequest inValue = new Recargaqui.GetBalanceRequest();
            inValue.Body = new Recargaqui.GetBalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Recargaqui.transactSoap)(this)).GetBalanceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.transactSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.transactSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.transactSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://187.217.102.146/recargaqui/transact.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.transactSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://187.217.102.146/recargaqui/transact.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            transactSoap,
            
            transactSoap12,
        }
    }
}
